package db

import "github.com/Augustin0/Types-Interfaces/Utils"

var DBEmpresas map[int]Utils.Empresa = map[int]Utils.Empresa{
	0:  {Name: "Banco BHD", Logo: "https://logos.com/bhd.jpg", Address: "Address1", Tel: "806-90"},
	1:  {Name: "Cafeteria M&M", Logo: "https://logos.com/M&M.jpg", Address: "Address3", Tel: "806-101"},
	2:  {Name: "Alexa Comedor", Logo: "https://logos.com/acomedor.jpg", Address: "Address3", Tel: "806-102"},
	3:  {Name: "Colmado Santana", Logo: "https://logos.com/colSANTANA.jpg", Address: "Address4", Tel: "806-103"},
	4:  {Name: "Disco Calderon", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	5:  {Name: "Salon The Best", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	6:  {Name: "Tienda J&R", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	7:  {Name: "Luisa Tienda", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	8:  {Name: "Pepes Col", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	9:  {Name: "Tu clinica", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	10: {Name: "Salud dental", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	11: {Name: "Mendez Bar", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	12: {Name: "Samanta Restaurante", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	13: {Name: "D' Perez Peluqueria", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	14: {Name: "Embutidos Marcos", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	15: {Name: "Jatna el mecanico", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	16: {Name: "Cyber coffe  Centro", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	17: {Name: "Samuel Electric", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	18: {Name: "Electronica Taller", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	19: {Name: "Todo Electronica", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	20: {Name: "Solo diseño web", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	21: {Name: "Desarrollo Android Company", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	22: {Name: "Solo API res", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	23: {Name: "The Hacker comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	24: {Name: "Go comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	25: {Name: "Node Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	26: {Name: "Java comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	27: {Name: "Java script Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	28: {Name: "Html Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	29: {Name: "CSS comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	30: {Name: "Vue comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	31: {Name: "IONIC comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	32: {Name: "Angular Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	33: {Name: "React Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	34: {Name: "Android Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
	35: {Name: "& Comunity", Logo: "https://logos.com/calderon.jpg", Address: "Address5", Tel: "806-104"},
}
